# Generated by Django 5.0.6 on 2024-05-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=50)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="station"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date_SZ", models.DateField(blank=True, null=True)),
                ("issue_date_RD", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="station_report.section",
                        verbose_name="дата выдачи СЗ и дата выдачи РД",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="section",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station_report.station",
                verbose_name="этапы производства",
            ),
        ),
    ]
