# Generated by Django 5.0.6 on 2024-05-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectiondate",
            name="comment",
        ),
        migrations.AddField(
            model_name="section",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
