# Generated by Django 5.0.6 on 2024-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_report", "0002_remove_sectiondate_comment_section_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="complate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания комплектации"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="start_work_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата начала работ"
            ),
        ),
    ]
