# Generated by Django 5.0.6 on 2024-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "station_report",
            "0002_alter_section_comment_alter_section_is_completed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_name",
            field=models.CharField(max_length=5, verbose_name="Название этапа"),
        ),
    ]
