# Generated by Django 5.0.6 on 2024-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_report", "0003_alter_section_section_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectiondate",
            name="issue_date_RD",
            field=models.DateField(default=None, verbose_name="Дата выдачи РД"),
        ),
        migrations.AlterField(
            model_name="sectiondate",
            name="issue_date_SZ",
            field=models.DateField(default=None, verbose_name="Дата выдачи СЗ"),
        ),
    ]
