# Generated by Django 5.0.6 on 2024-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_report", "0004_alter_sectiondate_issue_date_rd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectiondate",
            name="issue_date_RD",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи РД"
            ),
        ),
        migrations.AlterField(
            model_name="sectiondate",
            name="issue_date_SZ",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи СЗ"
            ),
        ),
    ]
