# Generated by Django 5.0.6 on 2024-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_report", "0005_alter_sectiondate_issue_date_rd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="issue_date_RD",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Дата выдачи РД"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="issue_date_SZ",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Дата выдачи СЗ"
            ),
        ),
        migrations.DeleteModel(
            name="SectionDate",
        ),
    ]
